version: "3.8"

services:
  api:
    container_name: backend-api-1
    build: .
    command: ["migrate", "npm", "start"]
    ports:
      - "4050:4050"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app

  worker:
    container_name: backend-worker-1
    build: .
    command: ["npm", "run", "worker"]
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app

  sqlite-web:
    container_name: backend-sqlite-web-1
    image: coleifer/sqlite-web
    entrypoint: ["sqlite_web", "--host", "0.0.0.0", "--port", "8080", "/data/sqlite.db"]
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      - app

  # Caddy service custom built with cloudflare dns plugin
  caddy:
    container_name: backend-caddy
    image: caddy-cloudflare:latest
    build:
      context: .
      dockerfile_inline: |
        FROM caddy:2.9-builder AS builder
        RUN xcaddy build --with github.com/caddy-dns/cloudflare
        FROM caddy:2.9-alpine
        COPY --from=builder /usr/bin/caddy /usr/bin/caddy
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
      - ./uploads:/app/uploads
    env_file:
      - .env
    networks:
      - app

networks:
  app:
    name: backend_app